sequenceDiagram
autonumber
box IotCore
participant credenciais
participant políticas
participant broker
end
credenciais ->> credenciais: Cria Thing com public e private key
credenciais ->> políticas: Associa certificado a uma política de autorização
credenciais ->> device: Salva certificado assinado no dispositivo
activate device
Note over credenciais,device: Criação de dispositivo seguro
device ->> credenciais: Envia certificado assinado
credenciais ->> credenciais: Valida certificado 
Note over credenciais,device: Autenticação
credenciais ->> políticas: Valida política de autorização para ação desejada
device ->> broker: gera conexão TLS
Note over device,broker: Conexão segura
device ->> broker: Tenta realizar ação
broker ->> políticas: Valida política de autorização
políticas ->> broker: Autoriza ação
device ->> broker: Realiza ação
Note over políticas,device: Autorização

