version: '3'

services:
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=mongodb
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=27017
      - MB_DB_USER=<mongo_user>
      - MB_DB_PASS=<mongo_password>
      - MB_DB_HOST=<mongo_host>
