sequenceDiagram
    participant Device as Dispositivo
    participant IotCore as IoT Core
    participant Kafka as Apache Kafka
    participant Mongo as MongoDB
    participant Metabase as Metabase
    participant Admin as Admin

Device ->> Device: Gera/Coleta dados
Device ->> IotCore: Envia certificados X.509
IotCore ->> IotCore: Verifica certificados

Note over Device, IotCore: Conexão autenticada e segura via TLS

Device ->> IotCore: Publica dados no tópico associado
IotCore ->> IotCore: Checa permissões nas políticas

Note over Device, IotCore: Autorização via políticas
Note over IotCore, Kafka: Autorizações via IAM Role (Lab Role)

IotCore ->> Kafka: Envia dados recebidos a fila em Kafka

Note over Kafka, Admin: Autorizações via credenciais (usuário, senha, IP)

Kafka ->> Mongo: Salva dados no banco NoSQL
Metabase ->> Mongo: Consulta dados para visualização via credenciais no container
Admin ->> Metabase: Utiliza login e senha para acessar Metabase



