name: Run Data Pipeline tests

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go environment
        run: |
          mkdir -p $HOME/go
          echo "export GOPATH=$HOME/go" >> $GITHUB_ENV
          echo "export PATH=$PATH:$HOME/go/bin" >> $GITHUB_ENV
        shell: bash

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Go Version
        run: go version
      - name: Test
        run: |
          cd src/tests 
          touch .env
          echo ${{ secrets.ENV_CONTENT}}  >> .env
          go test -v
