name: Download from S3

on:
  workflow_dispatch:

jobs:
  download_from_s3:
    runs-on: ubuntu-latest
name: Download from S3

on:
  workflow_dispatch:

jobs:
  download_from_s3:
    runs-on: ubuntu-latest

    steps:
    - name: Download file from S3
      run: |
        file_content=$(aws s3 cp s3://yourbucket/folder/local_file.txt -)
        echo "FILE_CONTENT=${file_content}" >> $GITHUB_ENV

    - name: Process the content
      run: |
        # Access the file content using the environment variable
        echo "${FILE_CONTENT}"
    steps:
    - uses: keithweaver/aws-s3-github-action@v1.0.0
      with:
        command: cp
        source: s3://infrastructure-state-terraform20240226124632827500000002/authentication-key/north_cert.pem
        destination: ./local-file.txt
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-1
